### ISSUE TITLE
Native macOS App

### ISSUE THREAD

**Issue by heyvito** [roytanck/wallpaper-generator#3]
Hey there, Roy! Found your project on Hacker News and immediately loved it. The web needs more lightweight (and gorgeous) projects like this!

Just a heads-up that I ported it into a native macOS app with a few features: https://github.com/heyvito/kabegami; left the due credit on readme, pointing to this repository.

Cheers! 🙌🏻

**Comment by roytanck** [comment]
This is very cool. Thank you!
